import './globals.css';
import { Layout } from './_components';

export const metadata = {
  title: 'World of Worlds',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  )
}
